newIssueWelcomeComment: "ğŸ‘‹ Salut et bienvenue ! Merci d'avoir ouvert cette issue. Nous allons la traiter dÃ¨s que possible ! ğŸš€"
newPRWelcomeComment: "Merci pour ta contribution ! Nous allons examiner ton PR et te donner un retour rapidement. ğŸ˜ƒ"
firstPRMergeComment: "ğŸ‰ FÃ©licitations pour ta premiÃ¨re contribution ! Merci et continue comme Ã§a ! ğŸš€"
